import type { Metadata } from "next";
<<<<<<< HEAD
import Navbar from "@/components/Navbar";
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "StudyBoard",
  description: "A study group task coordination app",
=======
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Samie's StudyBoard",
  description: "Generated by create next app",
>>>>>>> 641aad2650ce991ae14c58f433dc2a40c0546a92
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
<<<<<<< HEAD
        <Providers>
          <Navbar />
          {children}
        </Providers>
=======
        <Navbar/>
        {children}
>>>>>>> 641aad2650ce991ae14c58f433dc2a40c0546a92
      </body>
    </html>
  );
}
